spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academy_product_api
    username: root
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create